/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.Statement;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.NhanVien;
import java.sql.PreparedStatement;
import java.util.ArrayList;
/**
 *
 * @author Phuong Lan, Hoang Duc, Khai Truong
 */
public class showToaThuocJDialog extends javax.swing.JDialog {
    private Connection conn;
    private DefaultTableModel tblModel;
    public void connect(){
        try {
            String url="jdbc:oracle:thin:@localhost:1521:orcl";
            conn=DriverManager.getConnection(url,"system","user_java123");
        } catch (SQLException ex) {
            Logger.getLogger(BaseFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void inputTable(){
        tblModel=(DefaultTableModel)tblToaThuoc.getModel();
        int mahd=home.getMaHoaDon();
        txtMaHD.setText(mahd+"");
        int tinhtrang=0;
        try {
            connect();
            String query = "select T.LOAITHUOC, TT.SOLUONG, TT.TINHTRANG from SYS.QLPK_THUOC T, SYS.QLPK_TOATHUOC TT where T.MATHUOC=TT.MATHUOC AND MAHD=" + mahd;
            java.sql.Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(query);
            while(rs.next()){
                String loaiThuoc=rs.getString(1);
                int soLuong=rs.getInt(2);
                tinhtrang=rs.getInt(3);
                Object[] obj={loaiThuoc, soLuong};
                tblModel.addRow(obj);
            }
            
            if(tinhtrang==0){
                txtTinhTrang.setText("Chưa lấy");
            }
            else{
                txtTinhTrang.setText("Đã lấy");
            }
            
            int tienthuoc=0;
            String query2="select SUM(THANHTIEN) FROM SYS.QLPK_TOATHUOC WHERE MAHD="+mahd;
            java.sql.Statement stm1 = conn.createStatement();
            ResultSet rs1 = stm1.executeQuery(query2);
            while(rs1.next()){
                tienthuoc=rs1.getInt(1);
            }
            txtTienThuoc.setText(rutGonDoanhThu(tienthuoc)+" VNĐ");
            
            conn.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi lấy dữ liệu toa thuốc");
        }
    }
    
        public String rutGonDoanhThu(long money){
        ArrayList<String> arr=new ArrayList<>();
        while(money>999){
            long temp=money%1000;
            money/=1000;
            if(temp==0){
                arr.add(String.valueOf(temp)+"00");
            }else if(temp<=9){
                arr.add("00"+String.valueOf(temp));
            }else if(temp<=99){
                arr.add("0"+String.valueOf(temp));
            }else 
                arr.add(String.valueOf(temp));
        }
        arr.add(String.valueOf(money));
        String tien=" ";
        for(int j=arr.size()-1; j>0; j--){
            tien=tien+arr.get(j)+".";
        }
        tien=tien+arr.get(0);
        return tien;
    }
    
    public void showToaThuocInfo(){
        inputTable();
        txtMaHD.setEditable(false);
        txtTinhTrang.setEditable(false);
        txtTienThuoc.setEditable(false);
    }
    
    private BaseFrame home;
    public showToaThuocJDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        home=(BaseFrame) parent;
        showToaThuocInfo();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblToaThuoc = new javax.swing.JTable();
        btNhanThuoc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtTinhTrang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtTienThuoc = new javax.swing.JTextField();
        btThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(69, 123, 179));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 32)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TOA THUỐC");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(161, 161, 161)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(204, 204, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Mã hóa đơn");

        txtMaHD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tblToaThuoc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tblToaThuoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loại thuốc", "Số lượng"
            }
        ));
        jScrollPane1.setViewportView(tblToaThuoc);
        if (tblToaThuoc.getColumnModel().getColumnCount() > 0) {
            tblToaThuoc.getColumnModel().getColumn(0).setPreferredWidth(160);
            tblToaThuoc.getColumnModel().getColumn(0).setMaxWidth(200);
            tblToaThuoc.getColumnModel().getColumn(1).setPreferredWidth(60);
            tblToaThuoc.getColumnModel().getColumn(1).setMaxWidth(70);
        }

        btNhanThuoc.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        btNhanThuoc.setText("ĐÃ NHẬN THUỐC");
        btNhanThuoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNhanThuocActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Tình trạng");

        txtTinhTrang.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Tiền thuốc");

        txtTienThuoc.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        btThoat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btThoat.setText("THOÁT");
        btThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtTienThuoc, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMaHD))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtTinhTrang))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(btNhanThuoc)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btThoat)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtTinhTrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtTienThuoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btNhanThuoc)
                        .addGap(160, 160, 160)
                        .addComponent(btThoat)
                        .addGap(22, 22, 22))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btNhanThuocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNhanThuocActionPerformed
        try {
            int mahd        = home.getMaHoaDon();
            long tienKham   = 20000;
            long tienThuoc  = 0;
            
            // Sử dụng cho đồ án Java
            connect();
            
            String query = "SELECT SUM(ThanhTien) FROM SYS.QLPK_TOATHUOC WHERE MaHD='"+mahd+"'";
            Statement stm = conn.createStatement();
            ResultSet rs = stm.executeQuery(query);
            while(rs.next()){
                tienThuoc = rs.getLong(1);
            }
            
            query = "UPDATE SYS.QLPK_TOATHUOC SET TINHTRANG=? WHERE MAHD=?";
            PreparedStatement pre=conn.prepareStatement(query);
            pre.setInt(1, 1);
            pre.setInt(2, mahd);
            pre.executeUpdate();            
                       
            query = "UPDATE SYS.QLPK_HOADON SET TIENKHAM=?, THANHTIEN=? WHERE MAHD=?";
            PreparedStatement pre2 = conn.prepareStatement(query);
            pre2.setLong(1, tienKham);
            pre2.setLong(2, tienThuoc + tienKham);
            pre2.setInt(3, mahd);
            pre2.executeUpdate();
            
            int maThuoc = 0;
            long thanhTien = 0;
            String select = "SELECT MaThuoc, ThanhTien FROM SYS.QLPK_TOATHUOC WHERE MaHD='"+mahd+"'";
            Statement stm2 = conn.createStatement();
            ResultSet rs2 = stm2.executeQuery(select);
            while(rs2.next()){
                maThuoc = rs2.getInt(1);
                thanhTien = rs2.getLong(2);
                
                query = "UPDATE SYS.QLPK_THUOC SET DOANHTHU=? WHERE MATHUOC=?";
                PreparedStatement pre3 = conn.prepareStatement(query);
                pre3.setLong(1, thanhTien);
                pre3.setInt(2, maThuoc);
                pre3.executeUpdate();
            }
            
            JOptionPane.showMessageDialog(rootPane, "Ðã hoàn tất thanh toán");

            // Sử dụng cho mô tả bất đồng thời oracle
//            String query="{call CAPNHATTINHTRANG(?)}";
//            CallableStatement castm = conn.prepareCall(query);
//            castm.setInt(1, mahd);
//            castm.execute();
            
            conn.close();
            this.dispose();
        } 
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi cập nhập tình trạng toa thuốc!");
            Logger.getLogger(showToaThuocJDialog.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btNhanThuocActionPerformed

    private void btThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btThoatActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(showToaThuocJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(showToaThuocJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(showToaThuocJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(showToaThuocJDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                showToaThuocJDialog dialog = new showToaThuocJDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btNhanThuoc;
    private javax.swing.JButton btThoat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblToaThuoc;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtTienThuoc;
    private javax.swing.JTextField txtTinhTrang;
    // End of variables declaration//GEN-END:variables
}
